### PR TITLE
Add support of Kanji Mode

### PR DESCRIPTION
**Pull request by RexWzh**

### CODE REVIEW

**Comment by RexWzh** [comment]
## Main change
1. use `zero, unit` instead of `Poly([0]), Poly([1])`
2. move original tests of QRCode.jl into `test/tst_overall.jl`

---

> For a highly-optimized algorithm where bandwidth is the bottleneck, UInt8 vs Int can make a lot of difference in performance, e.g., https://github.com/JuliaImages/ImageMorphology.jl/pull/102#issuecomment-1165297247. But for QRCoders, it might be too early for this to make a difference.

I did some tests about type allocations:
   - It has slight effect when changing `func(::Int)` with `func(::Integer)`
   - However, the efficiency decreases observably when type conversion is involved
     ```jl
     struct foo
         data::Vector{UInt8}
     end
     data = rand(0:255, 10^4)
     uint8data = UInt8.(data)
     @btime sum(foo(data).data); # 4.105 μs
     @btime sum(foo(uint8data).data); # 836.509 ns
     ```
     In order to increase the code efficiency, we need to avoid type conversion as possible. (we might consider that in the later stage)

**Comment by johnnychen94** [comment]
Looks like there's a misunderstanding here about the type annotation on performance. I'll write up a few things and share it with you in private later this week.

**Comment by RexWzh** [comment]
I'm a little confused about the purpose of _**key word**_ and **_predefined values_**.

```jl
function qrcode( message::AbstractString
       , eclevel::ErrCorrLevel = Medium()
       ; version::Int = 0
       , compact::Bool = false )
```

Would it be better to write
```jl
function qrcode( message::AbstractString
       ; eclevel::ErrCorrLevel = Medium()
       , version::Int = 0 
       , compact::Bool = false)
```

**Comment by johnnychen94** [comment]
- keyword parameter doesn't participate in multiple dispatch
- in old Julia (<v1.0 I think), keyword parameter has large overhead. In Julia 1.8, it seems that the overhead of constant keyword parameter is optimized to "zero".

Choosing between keyword parameter and positional argument is a tradeoff between convenience and explicitly -- this is more of a design taste.

Because keyword parameter doesn't participate in multiple dispatch, it has to be type stable regardless of different value choices. For instance,

```julia
julia> struct M1 end

julia> struct M2 end

julia> f(; m) = m()
f (generic function with 1 method)

julia> g(m) = m()
g (generic function with 1 method)

julia> @code_warntype f(m=M1) # unstable
MethodInstance for (::var"#f##kw")(::NamedTuple{(:m,), Tuple{DataType}}, ::typeof(f))
  from (::var"#f##kw")(::Any, ::typeof(f)) in Main at REPL[3]:1
Arguments
  _::Core.Const(var"#f##kw"())
  @_2::NamedTuple{(:m,), Tuple{DataType}}
  @_3::Core.Const(f)
Locals
  m::DataType
  @_5::DataType
Body::Any
1 ─ %1  = Base.haskey(@_2, :m)::Core.Const(true)
│         Core.typeassert(%1, Core.Bool)
│         (@_5 = Base.getindex(@_2, :m))
└──       goto #3
2 ─       Core.Const(:(Core.UndefKeywordError(:m)))
└──       Core.Const(:(@_5 = Core.throw(%5)))
3 ┄ %7  = @_5::DataType
│         (m = %7)
│   %9  = (:m,)::Core.Const((:m,))
│   %10 = Core.apply_type(Core.NamedTuple, %9)::Core.Const(NamedTuple{(:m,)})
│   %11 = Base.structdiff(@_2, %10)::Core.Const(NamedTuple())
│   %12 = Base.pairs(%11)::Core.Const(Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}())
│   %13 = Base.isempty(%12)::Core.Const(true)
│         Core.typeassert(%13, Core.Bool)
└──       goto #5
4 ─       Core.Const(:(Base.kwerr(@_2, @_3)))
5 ┄ %17 = Main.:(var"#f#3")(m, @_3)::Any
└──       return %17

julia> @code_warntype g(M1) # stable
MethodInstance for g(::Type{M1})
  from g(m) in Main at REPL[4]:1
Arguments
  #self#::Core.Const(g)
  m::Core.Const(M1)
Body::M1
1 ─ %1 = (m)()::Core.Const(M1())
└──      return %1
```

For our case, if we can ensure that output is always `Matrix{Bool}`, we're good to use keyword parameter.

**Comment by RexWzh** [comment]
# Abstract
1. Add support of Kanji mode
2. Separate `UTF8` mode from `Byte` mode (the `length` method for the two are different)
3. Minor changes on some of the functions

I summarize the followings that might need to be reviewed before merging this PR. Looking forward to your advice if convenient.

**Comment by RexWzh** [comment]
## matrix.jl -- line149
Here I have some questions about the efficiency of `makemask`.

Origin implement of `makemasks`.
```jl
"""
    makemasks(matrix::Array{Union{Bool,Nothing},2})

Create 8 bitmasks for a given matrix.
"""
function makemasks(matrix::Array{Union{Bool,Nothing},2})::Array{BitArray{2},1}
    n = size(matrix, 1)
    masks = [falses(size(matrix)) for _ in 1:8]

    # Weird indexing due to 0-based indexing in documentation
    for row in 0:n-1, col in 0:n-1
        isnothing(matrix[row+1, col+1]) || continue
        if (row ⊻ col) & 1 == 0
            masks[1][row+1, col+1] = true
        end
        if row & 1 == 0
            masks[2][row+1, col+1] = true
        end
        if col % 3 == 0
            masks[3][row+1, col+1] = true
        end
        if (row + col) % 3 == 0
            masks[4][row+1, col+1] = true
        end
        if (row >> 1 + col ÷ 3) & 1 == 0
            masks[5][row+1, col+1] = true
        end
        if (row & col & 1) + ((row * col) % 3) == 0
            masks[6][row+1, col+1] = true
        end
        if ((row & col & 1) + ((row * col) % 3)) & 1 == 0
            masks[7][row+1, col+1] = true
        end
        if (((row ⊻ col) & 1) + ((row * col) % 3)) & 1 == 0
            masks[8][row+1, col+1] = true
        end
    end
    return masks
end
```

I add a function `makemask` since only one mask is needed in **QRDecoders.jl** for each decoding.
```jl
_maskrules = Function[
    (x, y) -> (x ⊻ y) & 1,
    (x, _) -> x & 1,
    (_, y) -> y % 3,
    (x, y) -> (x + y) % 3,
    (x, y) -> (x >> 1 + y ÷ 3) & 1,
    (x, y) -> (x & y & 1) + (x * y % 3),
    (x, y) -> (x & y & 1 + x * y % 3) & 1,
    (x, y) -> ((x ⊻ y & 1) + (x * y % 3)) & 1
]
makemask(matrix::AbstractArray, k::Int)::BitArray{2} = makemask(matrix, _maskrules[k])
function makemask(matrix::AbstractArray, rule::Function)::BitArray{2}
    n = size(matrix, 1)
    mask = falses(size(matrix))
    for row in 1:n, col in 1:n
        mask[row, col] = isnothing(matrix[row, col]) && iszero(rule(row - 1, col - 1))
    end
    return mask
end
```

I would rewrite the `makemasks` as following.
```jl
makemasks(matrix::AbstractMatrix) = makemask.(Ref(matrix), 1:8)
```

But it would be much slower.
```jl
using BenchmarkTools
using QRCoders: empytmatrix
matrix = empytmatrix(20)

@btime makemasks(matrix); # 85.790 μs (17 allocations: 10.23 KiB)
@btime makemask.(Ref(matrix), 1:8); # 215.263 μs (20 allocations: 10.31 KiB)
```

The decrease in efficiency is partly due to the assignment operation. It would be better if writing
```jl
function makemask(matrix::AbstractArray, rule::Function)::BitArray{2}
    n = size(matrix, 1)
    mask = falses(size(matrix))
    @inbounds for row in 1:n, col in 1:n
        if isnothing(matrix[row, col]) && iszero(rule(row - 1, col - 1))
            mask[row, col] = true
        end
    end
    return mask
end

@btime makemask.(Ref(matrix), 1:8); # 131.314 μs (20 allocations: 10.31 KiB)
```

But still, it's a bit slower than the direct method `makemasks`.

Here is my question:
   - I try to avoid `if` method to trigger higher performance of the for-loop but failed(and cost more)
   - The new method is still a bit slower `makemasks`, is that caused by the function call.

**Comment by RexWzh** [comment]
## table.jl -- line 11

I use the `read` function to initialize `kanji`.

```jl
"""
Shift-JIS characters download from: https://www.romhacking.net/documents/179/.
"""
_kanji = split.(split(strip(read("src/Kanji.tbl", String)), '\n'), '=')

"""
Allowed characters for `Kanji()` mode.
"""
const kanji = Dict{AbstractChar, Int}(
  first(j) => parse(Int, i; base=16) for (i, j) in _kanji)
```

This only works in `QRCoders.jl`. When I try `using QRCoders` in `QRDecoders.jl`, it would throw file path error. So I use `include` method instead.

My questions are, is it reasonable to initialize variables with text file especially when the file is large, and how to avoid path error when dealing with files.

**Pull request merged**
